name: build-preview

on:
  push:
    branches:
      - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish Image
        uses: craftech-io/package-action@v3.1.0
        with:
          image_name: thecodingstarstuff-blog-preview
          tags: latest
          access_token: ${{ secrets.GITHUB_TOKEN }}
